Vagrant.configure("2") do |config|
  config.vm.box = "fscm/cassandra"
  config.vm.network "forwarded_port", guest: 9042, host: 9042
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
